wholeslidedata:
    default:
        image_sources:
            path: 'not set'
        
        annotation_sources:
            path: 'not set'
        
        annotation_parser:
            shape: [128, 128]
        
        batch_shape:
            batch_size: 8
            shape: [128, 128, 3]
            spacing: 0.5

        dataset:
            copy_path: /home/user/data/